project:
  type: website
  output-dir: docs

# Meta
description-meta: "Derek Wang personal website"
author-meta: "Derek Wang"

website:
  title: "Derek Wang"
  image: "https://quarto.org/quarto.png"
  description: "Derek Wang personal website"
 
  navbar:
    background: light 

    left: 
      - text: Home
        href: index.qmd
      
      - text: CV
        href: cv.qmd

      - text: Research
        href: research.qmd

      - text: Notes
        href: notes.qmd

      - text: Design
        href: design.qmd

      - text: Photos
        href: photos.qmd   

    right: 
      - icon: github
        href: https://github.com/wxrderek
        target: _blank 
  
  page-navigation: true
  
  page-footer: 
    left: "[Derek Wang](https://www.linkedin.com/in/xiran-derek-wang/) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built on the [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) by [Dr. Gang He](http://drganghe.github.io)"
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  site-url: https://wxrderek.github.io/

  draft-mode: unlinked
  
  repo-url: https://github.com/wxrderek/wxrderek.github.io.git
  
  open-graph: true   
  google-analytics:
    tracking-id: ""
    anonymize-ip: true 

bibliography: references.bib

# author:
#   name: "Derek Wang"
#   affiliation: "Duke University"
#   email: "xiran.wang@duke.edu"

format:
  html:
    meta:
      - name: google-site-verification
        content: t4mEvu_02oJIFKWntH-yH8PItK4wISyuL3h2MS7tC7g
    
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/wxrderek\.github\.io\/custom'
    
    include-in-header: 
      - "files/includes/head.html"
      - text:
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">

