project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Derek Wang"

website:
  title: "Xiran 'Derek' Wang"
  image: "https://quarto.org/quarto.png"
  description: "Derek Wang Academic Website"
 
  navbar:
    background: light 

    left: 
      - text: Home
        href: index.qmd

      - text: Research
        href: research.qmd

      - text: Notes
        href: notes.qmd       

    right: 
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank 
  
  page-navigation: true
  
  page-footer: 
    left: "[Derek Wang](https://www.linkedin.com/in/xiran-derek-wang/) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Built on the [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) by [Dr. Gang He](http://drganghe.github.io)"
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/wxrderek/wxrderek.github.io.git
#  repo-actions: [edit, issue, source]
  
  open-graph: true 
  
  site-url: "https://wxrderek.github.io/"
  
  google-analytics:
    tracking-id: ""
    anonymize-ip: true 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/wxrderek\.github\.io\/custom'
    include-in-header: 
      - "files/includes/_academic.qmd"
      - text:
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">

